KiiPlatform/KiiThingSDK-Embedded

gt202/gt202_kii_adapter.c
gt202/gt202_kii_adapter.h
gt202/kii_cloud_demo.c
gt202/kii_mqtt_socket.c
gt202/prv_kii_recv_copy.c
gt202/prv_kii_recv_zero_copy.c
gt202/prv_kii_setting.h

GT202向けのコードでデフォルトHttpClientを使用するように修正しました。

use default http client.

---

Linux/example.c
Linux/kii_init_impl.c
Linux/kii_init_impl.h
kii/kii_thing.c
tests/large_test/kii_test.cc

I moved kii_init function to sdk layer.
This must be going to be merged after KiiPlatform/KiiThingSDK-Embedded-Core#64 is merged.
After KiiPlatform/KiiThingSDK-Embedded-Core#64, We need to update kii-core submodule.
related issue: #85

kii_init function is moved to sdklayer.

---

kii-core/tests/small_test/Makefile
kii-core/tests/small_test/kii_test.cc

kii-coreのスモールテストを追加しました。
Issue: #98

Add kii-core small tests

---

Linux/kii_socket_impl.c
kii/kii_mqtt.c
kii/kii_push.c

kiiPush_recvMsgTaskをリファクタリングしました。
ping reqでネットワーク断を検出した後に、push installationを行わずにMQTTサーバへのconnectとsubscribeを行なうよう修正しました。

refactor kiiPush_recvMsgTask.

---

kii-core/kii_core.c
kii-core/kii_core.h
kii/Doxyfile
kii/kii_core_hidden.h
kii/kii_thing.c

Related issue No 785.
Related PR #107

Initializing methods with info are added.

---

kii-core/kii_core.c
kii-core/tests/small_test/kii_test.cc

I found a bug in `kii_core_init()`. It assign APP ID to `kii_core#app_key` field.
I fixed to assign APP KEY to `kii_core#app_key` field.
I also fix small tests. These tests are not check x-kii-sdk header. I fix small tests to check x-kii-sdk header.

Fix small test

---

tests/small_test/Makefile
tests/small_test/kii_test.cc

ユニットテストを追加しました。
push_start_routineに関しては、スレッドの使用や内部関数のstatic宣言などによりユニットテストでは対応できなかったのでテストを作成していません。
Issue: #100

Add small tests

---

kii-core/kii_core.c
kii-core/kii_core.h
kii/kii.h
kii/kii_core_hidden.h

Related issue No. 900
Release version 1.1.5

Site EU is added.

---

tests/large_test/kii_test.cc

Related to #117,  I added tests for KiiThingSDK-Embedded level.
Tests for following functions are added:
* `kii_object_upload_body_at_once()`
* `kii_object_upload_body()`

Binary upload test

---

gt202/kii_task_impl.c
gt202/kii_task_impl.h

gt202側は引数消すだけでした。マージをお願いします。
Issue: #129

fix task_create_cb in gt202.

---

kii/kii.h

https://github.com/KiiPlatform/thing-if-ThingSDK/pull/65 にてタスク名の変更指示が出たので修正しました。

change task name.

---

kii/README.mkd
kii/kii_mqtt.c

MQTTコネクトの際にポートを選択できるように修正しました。レビューをお願いします。
Issue: #142

use port_ssl

---

kii-core/kii_cl_parser.c
kii-core/kii_cl_parser.h
kii-core/kii_core.c
kii-core/kii_core.h
tests/small_test/content_length_test.cc

Check content-length to stop receiving data from the socket.

Content length check

---

Makefile
kii-core/kii_cl_parser.c
kii/kii_push.c

Fixed warning.

---

.circleci/config.yml
.gitignore
kii/kii.c
tests/large_test/.gitignore
tests/large_test/Makefile

- Enable Circle CI build
- Refactored build system.

Imprv build

---

kii/kii.c
kii/kii.h
kii/kii_impl.h
kii/kii_object.c
kii/kii_thing.c
tests/large_test/object_test.cpp

Implement object post.

---

kii/kii.h
kii/kii_object.c
tests/large_test/object_test.cpp

Implemented DELETE object method.

Object delete

---

.vscode/settings.json
kii/kii.h
kii/kii_impl.h
kii/kii_object.c
tests/large_test/large_test.h
tests/large_test/object_test.cpp

Added Object body upload/ download API. Body data is handled by stream APIs.

Object body upload/ download

---

kii/kii.h
kii/kii_server_code.c
tests/large_test/server_code_test.cpp

Servercode exec API

---

kii/kii_api_call.c
kii/kii_req_impl.c

Handle slist allocation error.

Slist allocation failure

---

kii/kii.h
kii/kii_mqtt.c

- Refactor logging macro with VA macro.
- Removed redundant logging.

Refactor logging macros.

---

Linux/example.c
Linux/example.h
kii-core/kii_core.c
kii-core/kii_core.h
kii/kii.h
kii/kii_thing.c
tests/large_test/kii_test.cc

- add `binary-body-length` parameter 
- add large test to upload json format state
- switch test app to new one
- add example to upload state

Upload thing state[Implementation]

---

Linux/example.c
Linux/example.h
kii-core/kii_core.c
kii-core/kii_core.h
kii-core/linux/kii_core_init.c
kii-core/tests/small_test/kii_test.cc
kii/kii.h
kii/kii_thing.c
tests/large_test/kii_test.cc
tests/small_test/kii_test.cc

Release v1.2.6
